// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mode_Rcpp
String mode_Rcpp(IntegerVector x);
RcppExport SEXP mypackage_mode_Rcpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    __result = Rcpp::wrap(mode_Rcpp(x));
    return __result;
END_RCPP
}
// simplify2array_Rcpp
RObject simplify2array_Rcpp(List x);
RcppExport SEXP mypackage_simplify2array_Rcpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    __result = Rcpp::wrap(simplify2array_Rcpp(x));
    return __result;
END_RCPP
}
