# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' mode_Rcpp
#' @description
#' This function determines the most frequently occurring value in an integer vector(mode).
#' 
#' @details
#' ARGUMENTS:
#' x - an integer vector
#'
#' RETURN VALUE:
#' a string value
#'
#' @family fungroup
#' @export
mode_Rcpp <- function(x) {
    .Call('mypackage_mode_Rcpp', PACKAGE = 'mypackage', x)
}

#' @title
#' simplify2array_Rcpp
#' @description
#' This function mimics the behavior of the simplify2array fucntion as close as possible.
#' 
#' @details
#' ARGUMENTS:
#' x - a list numeric values
#'
#' RETURN VALUE:
#' list or matrix
#'
#' @family fungroup
#' @export
simplify2array_Rcpp <- function(x) {
    .Call('mypackage_simplify2array_Rcpp', PACKAGE = 'mypackage', x)
}

